# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="/home/$USER/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
# ZSH_THEME="agnoster"
ZSH_THEME="evan"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in ~/.oh-my-zsh/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to automatically update without prompting.
# DISABLE_UPDATE_PROMPT="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS=true

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in ~/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

prompt_context() {}
zle_highlight+=(paste:none)

stty -ixon -echoctl

setopt inc_append_history
setopt share_history

export VISUAL=vim
export TERMINAL=kitty
export EDITOR="$VISUAL"
export PATH=$PATH:/home/$USER/myconfig/scripts
export PATH=/home/$USER/Dropbox/bin:$PATH
export PATH=$PATH:/home/$USER/.cargo/bin
export PATH=$PATH:/home/$USER/go/bin

export LESS_TERMCAP_mb=$'\e[1;94m'
export LESS_TERMCAP_md=$'\e[1;94m'
export LESS_TERMCAP_me=$'\e[0m'
export LESS_TERMCAP_se=$'\e[0m'
export LESS_TERMCAP_so=$'\e[100m'
export LESS_TERMCAP_ue=$'\e[0m'
export LESS_TERMCAP_us=$'\e[93m'
export GROFF_NO_SGR=1

# alias sudo='sudo -E env "PATH=$PATH"'
alias neovim="nvim"
alias v="nvim"
alias q="exit"
alias :q="exit"
alias rm="rm -r"
alias cp="rsync -r"
alias df="df -h"
alias ru='trans -brief en:ru'
alias cpuhp='ps -eo pcpu,pid,user,args | sort -k 1 -r | head -4'
alias watch="watch -t"
alias weather="curl wttr.in"
alias ag="ag --color-match '1;33' --color-line-number '0;34'"
alias rg="rg -F"
alias tmux="tmux -u"
alias UP="vim +PlugUpdate +CocUpdateSync +qa && solus up"
alias beep="notify-send beep"

alias lock="~/myconfig/lockscreen/lock.sh"
alias suspend="~/myconfig/lockscreen/lock.sh -s"
alias logout="dm-tool lock"

export cores=`grep -c ^processor /proc/cpuinfo`
# alias make='make -j $cores'
alias gdb='gdb -q -ex "set prompt \033[0;32m(gdb) \033[0m"'

alias CAPS='xdotool key Caps_Lock'
alias caps='xdotool key Caps_Lock'

alias gfr='git fetch && git reset --hard origin/master'
alias gri='git rebase -i HEAD~$(git rev-list --count HEAD ^origin/master)'

# FZF
if fzf --version &> /dev/null; then
    source /usr/share/fzf/key-bindings.zsh
    export FZF_DEFAULT_COMMAND='rg --files'
    export FZF_DEFAULT_OPTS='--height 20% --layout=reverse --border'
    export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
    export FZF_ALT_C_COMMAND="fd --type d"
fi

prompt_color() {
    if [ $? -ne 0 ]; then
        echo -n "%{$fg_bold[red]%}"
    elif [ -d ~/work ]; then
        echo -n "%{$fg_bold[blue]%}"
    else
        echo -n "%{$fg_bold[green]%}"
    fi
}

PROMPT='$(prompt_color)%2~ %B>%b %F{default}'

# WORK
if [ -d ~/work ]; then
    export PATH=$PATH:/home/$USER/myconfig/scripts/work
    export TMUX_MAIN_COLOUR=colour113
else
    export TMUX_MAIN_COLOUR=colour105

    prompt_dir() {
        prompt_segment green $CURRENT_FG '%~'
    }
fi

