# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:$HOME/.local/bin:/usr/local/bin:$PATH

# Path to your Oh My Zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time Oh My Zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="evan"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in $ZSH/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment one of the following lines to change the auto-update behavior
# zstyle ':omz:update' mode disabled  # disable automatic updates
# zstyle ':omz:update' mode auto      # update automatically without asking
# zstyle ':omz:update' mode reminder  # just remind me to update when it's time

# Uncomment the following line to change how often to auto-update (in days).
# zstyle ':omz:update' frequency 13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# You can also set it to another string to have that shown instead of the default red dots.
# e.g. COMPLETION_WAITING_DOTS="%F{yellow}waiting...%f"
# Caution: this setting can cause issues with multiline prompts in zsh < 5.7.1 (see #5765)
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='nvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch $(uname -m)"

# Set personal aliases, overriding those provided by Oh My Zsh libs,
# plugins, and themes. Aliases can be placed here, though Oh My Zsh
# users are encouraged to define aliases within a top-level file in
# the $ZSH_CUSTOM folder, with .zsh extension. Examples:
# - $ZSH_CUSTOM/aliases.zsh
# - $ZSH_CUSTOM/macos.zsh
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

prompt_context() {}
zle_highlight+=(paste:none)

stty -ixon -echoctl

setopt inc_append_history
setopt share_history

export QT_QPA_PLATFORM=wayland
export ELECTRON_OZONE_PLATFORM_HINT=wayland
export ELECTRON_ENABLE_WAYLAND=1
export GDK_BACKEND=wayland,x11

export VISUAL=nvim
export TERMINAL=kitty
export EDITOR="$VISUAL"
export PATH=$PATH:/usr/local/bin
export PATH=$PATH:/usr/sbin/
export PATH=$PATH:/home/$USER/myconfig/scripts
export PATH=$PATH:/home/$USER/.config/sway/device/scripts
export PATH=/home/$USER/Dropbox/bin:$PATH
export PATH=$PATH:/home/$USER/.cargo/bin
export PATH=$PATH:/home/$USER/go/bin
export PATH=$PATH:/home/$USER/.local/bin

export LESS_TERMCAP_mb=$'\e[1;94m'
export LESS_TERMCAP_md=$'\e[1;94m'
export LESS_TERMCAP_me=$'\e[0m'
export LESS_TERMCAP_se=$'\e[0m'
export LESS_TERMCAP_so=$'\e[100m'
export LESS_TERMCAP_ue=$'\e[0m'
export LESS_TERMCAP_us=$'\e[93m'
export GROFF_NO_SGR=1

retry() {
    retry_until_success.sh "$@"
}

# alias sudo='sudo -E env "PATH=$PATH"'
alias neovim="nvim"
alias v="nvim"
alias q="exit"
alias :q="exit"
alias rm="rm -r"
# alias cp="rsync -r"
alias df="df -h"
alias ru='trans -brief en:ru'
alias cpuhp='ps -eo pcpu,pid,user,args | sort -k 1 -r | head -4'
alias watch="watch -t"
alias weather="curl wttr.in"
alias ag="ag --color-match '1;33' --color-line-number '0;34'"
alias rg="rg -F"
alias tmux="tmux -u"
alias UP="neovim +PlugUpgrade +PlugUpdate +CocUpdateSync +qa && solus up"
alias beep="notify-send beep"
alias rv="sed -i -e 's/release-cursor=shift+f12/release-cursor=ctrl+alt/g' ~/Downloads/console.vv && remote-viewer ~/Downloads/console.vv"

if [[ "$XDG_SESSION_TYPE" == wayland ]] || [[ -n "$WAYLAND_DISPLAY" ]]; then
    alias lock='~/myconfig/scripts/swaylock.sh'
    alias suspend='~/myconfig/scripts/suspend.sh'
else
    alias lock='~/myconfig/scripts/i3lock/lock.sh'
    alias suspend='~/myconfig/scripts/i3lock/lock.sh -s'
    alias logout='dm-tool lock'
    alias CAPS='xdotool key Caps_Lock'
    alias caps='xdotool key Caps_Lock'
fi

export cores=`grep -c ^processor /proc/cpuinfo`
# alias make='make -j $cores'
alias gdb='gdb -q -ex "set prompt \033[0;32m(gdb) \033[0m"'

alias gfr='git fetch && git reset --hard origin/master'
alias gri='git rebase -i HEAD~$(git rev-list --count HEAD ^origin/master)'

# FZF
if fzf --version &> /dev/null; then
    source /usr/share/fzf/key-bindings.zsh
    export FZF_DEFAULT_COMMAND='rg --files'
    export FZF_DEFAULT_OPTS='--height 20% --layout=reverse --border'
    export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
    export FZF_ALT_C_COMMAND="fd --type d"
fi

prompt_color() {
    if [ $? -ne 0 ]; then
        echo -n "%{$fg_bold[red]%}"
    elif [ -d ~/work ]; then
        echo -n "%{$fg_bold[blue]%}"
    else
        echo -n "%{$fg_bold[green]%}"
    fi
}

PROMPT='$(prompt_color)%2~ %B>%b %F{default}'

export PATH=$PATH:/home/$USER/myconfig/scripts/work

# WORK
if [ -d ~/work ]; then
    export PATH=$PATH:/home/$USER/myconfig/scripts/work
    export TMUX_MAIN_COLOUR=colour113

    # Source the workspace environment setup
    if [ -f ~/Downloads/workspace_secure/workspace_env.sh ]; then
        source ~/Downloads/workspace_secure/workspace_env.sh
    fi
else
    export TMUX_MAIN_COLOUR=colour105

    prompt_dir() {
        prompt_segment green $CURRENT_FG '%~'
    }
fi


# autoload -Uz compinit
# zstyle ':completion:*' menu select
# fpath+=~/.zfunc
# compinit -D

autoload -Uz compinit
fpath+=~/.zfunc
compinit




# eval "$(starship init zsh)"
