#!/bin/bash

# 1 - left click, 2 - middle click, 3 - right click, 4 - up wheel, 5 - down wheel.

if [[ ! -z "${BLOCK_BUTTON}" ]]; then
    ~/myconfig/scripts/cpufreq > /dev/null
fi

COLOR_DEFAULT="#DEDEDE"
COLOR_RED="#FF0000"
COLOR_ORANGE="#FFAE00"
COLOR_YELLOW="#FFF600"
COLOR_GREEN="#A8FF00"

FREQ=$(($(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq)/1000))
GFREQ=$(echo "$(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq)\
        1000000" | awk '{printf "%.1f", $1 / $2}')
CPUSAGE=$(top -bn1 | grep "Cpu(s)" | \
        sed "s/.*, *\([0-9.]*\)%* id.*/\1/" | \
        awk '{printf "%2.0f", 100 - $1}')
CURFREQ=$(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq)
MAXFREQ=$(cat /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_max_freq)
MIDFREQ=$(($MAXFREQ/2))
MINFREQ=$(cat /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_min_freq)
NUMPROC=$(nproc --ignore=1)

if ((CURFREQ > MINFREQ)); then
    if ((CURFREQ < MAXFREQ)); then
        COLOR_DEFAULT=$COLOR_YELLOW
    fi
else
    COLOR_DEFAULT=$COLOR_GREEN
fi

echo -n "CPU ${GFREQ} ${CPUSAGE}% "

NUM_DIRS="$(ls /sys/class/hwmon/ | wc -l)"
((NUM_DIRS=NUM_DIRS-1))

for x in /sys/class/hwmon/hwmon[0-$NUM_DIRS]; do
    if grep -q "coretemp" "$x/name"; then
        TEMP="$(($(cat $x/temp1_input)/1000))"
    fi
done

if [[ $TEMP -ge 85 ]];then
    COLOR_DEFAULT=$COLOR_RED
fi

echo "${TEMP}°C "
echo
echo "$COLOR_DEFAULT"
