#!/bin/bash

red="#FF0000"
orange="#FFAE00"
yellow="#FFF600"
green="#A8FF00"

FREQ=$(($(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq)/1000))
GFREQ=$(echo "$(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq)\
        1000000" | awk '{printf "%.1f", $1 / $2}')
CPUSAGE=$(top -bn1 | grep "Cpu(s)" | \
        sed "s/.*, *\([0-9.]*\)%* id.*/\1/" | \
        awk '{printf "%2.0f", 100 - $1}')
CURFREQ=$(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq)
MAXFREQ=$(cat /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_max_freq)
MIDFREQ=$(($MAXFREQ/2))
MINFREQ=$(cat /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_min_freq)
NUMPROC=$(nproc --ignore=1)

if ((CURFREQ > MINFREQ)); then
    if ((CURFREQ < MAXFREQ)); then
        COLOR=$yellow
    fi
else
    COLOR=$green
fi

echo -n "CPU ${GFREQ} ${CPUSAGE}% "


TEMP=$(($(cat /sys/class/hwmon/hwmon2/temp1_input)/1000))

if [[ $TEMP -ge 65 ]];then
    COLOR=$red
fi

echo "${TEMP}°C "
echo
echo "$COLOR"

