#!/bin/bash

layout=$(xset -q | grep -A 0 'LED' | cut -c59-67)
if [[ $layout -eq "000000000" || $layout -eq "000000002" ]]; then
    layout=US
elif [[ $layout -eq "00001000" || $layout -eq "00001002" ]]; then
    layout=RU
fi
echo -n " $layout "

