#!/bin/bash
echo "Enter S/N of your OLT: "
read SN
echo "Enter MAC address: "
read MAC
echo "Enter IP address: "
read IP
SNMAC=`echo $SN$MAC | md5sum | cut -d ' ' -f 1`
token=`echo $SNMAC$IP | md5sum | cut -d ' ' -f 1`
for ((i=1; i<32; i+=8)); do
		passwd="$passwd`echo $token | cut -b $i-$(($i+1))`"
	done
	echo "Your password: $passwd"
