#!/bin/bash

# https://asus-linux.org/
# https://gitlab.com/asus-linux/asusctl

# set -e
#
# source ~/myconfig/scripts/common_funcs.sh
#
# set -x

# sudo eopkg it clang-devel
# sudo eopkg it fontconfig-devel
# sudo eopkg it cmake
# sudo eopkg it libxkbcommon-devel
# sudo eopkg it rust
# sudo eopkg it seatd-devel
# sudo eopkg it libinput-devel
#
# git checkout 6.1.12

# ? sudo eopkg it egl-gbm-devel

# cd /tmp/

# rm -rf /tmp/asusctl
# gclonecd https://gitlab.com/asus-linux/asusctl
# apply patch !
# make
# sudo make install
# systemctl daemon-reload && systemctl restart asusd

# cp


 # > supergfxctl -S
# off
 # > supergfxctl -g
# Integrated

# ~ > cat /etc/supergfxd.conf
# {
  # "mode": "Integrated",
  # "vfio_enable": false,
  # "vfio_save": false,
  # "always_reboot": false,
  # "no_logind": false,
  # "logout_timeout_s": 180,
  # "hotplug_type": "Std"
# }

# echo "PWM enable values:" && for i in {1..3}; do echo -n "pwm${i}_enable: "; cat "/sys/class/hwmon/hwmon10/pwm${i}_enable" 2>/dev/null; echo; done && echo && echo "CPU Fan (pwm1) actual values:" && for i in {1..8}; do echo -n "Point $i: "; cat "/sys/class/hwmon/hwmon10/pwm1_auto_point${i}_temp" 2>/dev/null; echo -n "°C -> "; cat "/sys/class/hwmon/hwmon10/pwm1_auto_point${i}_pwm" 2>/dev/null; echo " PWM"; done
