#!/bin/bash

# https://asus-linux.org/
# https://gitlab.com/asus-linux/asusctl

# set -e
#
# source ~/myconfig/scripts/common_funcs.sh
#
# set -x

# sudo eopkg it clang-devel
# sudo eopkg it fontconfig-devel
# sudo eopkg it cmake
# sudo eopkg it libxkbcommon-devel
# sudo eopkg it rust
# sudo eopkg it seatd-devel
# sudo eopkg it libinput-devel
#
# git checkout 6.0.12

# ? sudo eopkg it egl-gbm-devel

# cd /tmp/

# rm -rf /tmp/asusctl
# gclonecd https://gitlab.com/asus-linux/asusctl
# apply patch !
# make
# sudo make install
# systemctl daemon-reload && systemctl restart asusd

# cp

