#!/bin/bash

workspace_secure_root() {
    local dir

    dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
    echo "${dir}"
}

workspace_secure_repo_root() {
    local dir

    dir="$(workspace_secure_root)"
    (cd "${dir}/../../.." && pwd)
}

workspace_secure_log() {
    echo "[workspace_secure] $*"
}

workspace_secure_reset_dir() {
    local target_dir="$1"

    rm -rf "${target_dir}"
    mkdir -p "${target_dir}"
}

workspace_secure_copy_tree() {
    local source_dir="$1"
    local target_dir="$2"

    mkdir -p "${target_dir}"
    cp -a "${source_dir}/." "${target_dir}/"
}

workspace_secure_prepare_env_file() {
    local env_file="$1"

    cat > "${env_file}" <<'EOF'
# Generated by workspace_secure/init_workspace.sh
# shellcheck shell=sh

EOF
}

workspace_secure_append_env_path() {
    local env_file="$1"
    local path_value="$2"
    local label="${3:-}"
    local export_line

    export_line="export PATH=\"${path_value}:\$PATH\""

    touch "${env_file}"

    if grep -Fqx "${export_line}" "${env_file}"; then
        return
    fi

    if [ -n "${label}" ]; then
        printf '# %s\n' "${label}" >> "${env_file}"
    fi

    printf '%s\n' "${export_line}" >> "${env_file}"
}
