#!/bin/bash

SNAME="[CONFIG]"

if [[ -n $SSH_CONNECTION ]]; then
    SNAME="SSH $SNAME"
fi

tmux has-session -t "$SNAME" 2> /dev/null
test $? -eq 0 && tmux attach -t "$SNAME" && exit

tmux new-session -s "$SNAME" -n myconfig -d
tmux send-keys -t "$SNAME" " cd myconfig && sleep 1; vg" C-m
tmux split-window -h -t "$SNAME"
tmux send-keys -t "$SNAME" " cd myconfig && clear" C-m
tmux select-layout -t "$SNAME" main-vertical

tmux select-window -t "$SNAME":1

tmux attach -t "$SNAME"

