#!/bin/bash

cd ~/projects/ltp-n/firmware/scripts

start_myqemu () {
    while true; do
        ./run_qemu.sh
        sleep 1
    done
}

restart_myqemu () {
    pkill qemu-system-x86
}

kill_myqemu () {
    killall myqemu
}

case "$1" in
    s) start_myqemu
        exit;;
    r) restart_myqemu
        exit;;
    k) kill_myqemu
        exit;;
    *? ) echo "bad arg '$1'"
        exit;;
esac
