#!/bin/bash

if [ -z "$1" ]; then
    echo "enter search mask in 'first arg'"
    exit
fi

find . -name "$1" -type f

read -p "Are you sure? " -n 1 -r
echo    # (optional) move to a new line
if [[ $REPLY =~ ^[Yy]$ ]]
then
    find . -name "$1" -type f -delete
fi

