#!/bin/bash

source ~/myconfig/scripts/common_funcs.sh

check_git

EDITOR="nvim"


commit () {
    $EDITOR $(git show $1 --pretty=format: --name-only) -p
}

mod () {
    $EDITOR $(git ls-files -m) -p
}

case "$1" in
    modified|mod|m) mod
        exit;;
    commit|com|c) commit $2
        exit;;
    *? ) echo "bad arg '$1'"
        exit;;
esac

if [ ! -z "$(git ls-files -m)" ]; then
    mod
else
    commit
fi

