#!/bin/bash

case "$1" in
    work|eltex)
        cd ~/Dropbox/work/vpn/
        sudo ~/Dropbox/work/vpn/vpn.sh
        exit;;
    *)
        cd ~/Dropbox/other/
        sudo openvpn node-us-56.protonvpn.net.udp.ovpn
        exit;;
esac

