#!/bin/bash

one () {
    xrandr --output eDP-1 --auto --primary --output HDMI-1 --off
    i3-msg "restart"
}

two () {
    xrandr --output HDMI-1 --auto --primary --output eDP-1 --off
    i3-msg "restart"
}

three () {
    xrandr --output HDMI-1 --auto --left-of eDP-1 --output eDP-1 --primary --auto
    i3-msg "restart"
}

four () {
    xrandr --output DP-1 --primary --auto --right-of HDMI-1 --output HDMI-1 --auto
    i3-msg "restart"
    # i3-msg "workspace 5, move workspace to output DP-1"
    # i3-msg "workspace 6, move workspace to output DP-1"
    # i3-msg "workspace 7, move workspace to output DP-1"
    # i3-msg "workspace 8, move workspace to output DP-1"
    # i3-msg "workspace 9, move workspace to output DP-1"
    # i3-msg "workspace 10, move workspace to output DP-1"
}

five () {
    xrandr --output eDP-1-1 --auto --primary --output HDMI-0 --off
    i3-msg "restart"
}

six () {
    xrandr --output HDMI-0 --auto --primary --output eDP-1-1 --off
    i3-msg "restart"
}

seven () {
    xrandr --output HDMI-0 --auto --left-of eDP-1-1 --output eDP-1-1 --primary --auto
    i3-msg "restart"
}

if [[ -n "$1"  ]]
then
    case "$1" in
        one|1) one; exit;;
        two|2) two; exit;;
        three|3) three; exit;;
        four|4) four; exit;;
        five|5) five; exit;;
        six|6) six; exit;;
        seven|7) seven; exit;;
        * ) echo "$1 is not an option"
            exit;;
    esac
else
    if [[ "$(xrandr | grep "*" | awk '{print $1;}')" == "1366x768" ]]; then
        three
    else
        one
    fi
fi

