#!/bin/bash

one () {
    xrandr --output eDP1 --auto --output HDMI1 --off
    i3-msg "restart"
}

two () {
    xrandr --output HDMI1 --auto --primary --output eDP1 --off
    i3-msg "restart"
}

three () {
    xrandr --output HDMI1 --auto --left-of eDP1 --output eDP1 --primary --auto
    # i3-msg "workspace 10, move workspace to output eDP1"
    i3-msg "restart"
    # i3-msg "workspace 1, move workspace to output HDMI1"
    # i3-msg "workspace 2, move workspace to output HDMI1"
    # i3-msg "workspace 3, move workspace to output HDMI1"
    # i3-msg "workspace 4, move workspace to output HDMI1"
    # i3-msg "workspace 5, move workspace to output HDMI1"
}

if [[ -n "$1"  ]]
then
    case "$1" in
        one) one; exit;;
        two) two; exit;;
        three) three; exit;;
        * ) echo "$1 is not an option"
            exit;;
    esac
else
    if [[ "$(xrandr | grep "*" | awk '{print $1;}')" == "1366x768" ]]; then
        three
    else
        one
    fi

fi

