#!/bin/bash

SNAME="REMOTE"

if [[ -n $SSH_CONNECTION ]]; then
    SNAME="SSH $SNAME"
fi

tmux has-session -t "$SNAME" 2> /dev/null
test $? -eq 0 && tmux attach -t "$SNAME" && exit

tmux new-session -s "$SNAME" -d
tmux send-keys -t "$SNAME" " pico 1"

# tmux new-window -t "$SNAME" -n ttyUSB1
# tmux send-keys -t "$SNAME" " picocom -b 115200 /dev/ttyUSB1" C-m

tmux new-window -t "$SNAME"
# tmux send-keys -t "$SNAME" "myqemu s" C-m
tmux split-window -h -t "$SNAME"

tmux select-window -t "$SNAME":1

tmux attach -t "$SNAME"

